# Generated by Django 4.0.5 on 2022-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googletakvim', '0002_crud_delete_worklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='worklist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iş_tipi', models.TextField()),
                ('durum', models.TextField()),
                ('öncelik', models.TextField()),
                ('atanan', models.TextField()),
                ('hedef_sürüm', models.TextField()),
                ('kalan_zaman', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CRUD',
        ),
    ]
