# Generated by Django 4.0.5 on 2022-07-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googletakvim', '0003_worklist_delete_crud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklist',
            old_name='id',
            new_name='ticketid',
        ),
    ]
