# Generated by Django 4.0.5 on 2022-07-21 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioncheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='versioncheckv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionname', models.CharField(max_length=20)),
                ('exportdate', models.DateTimeField()),
                ('state', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=32)),
                ('importdate', models.DateTimeField(default=datetime.datetime(2022, 7, 21, 14, 14, 40, 573629))),
            ],
        ),
        migrations.DeleteModel(
            name='version_check',
        ),
    ]
